name: Build Docker Image

on:
  push:
    branches:
      - main  # Change to your desired branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t your-image-name:latest .  # Change to your desired image name

      - name: List Docker images
        run: docker images
        
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.36.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.36.0_Linux-64bit.deb

      - name: Run Trivy scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL your-image-name:latest  # Change as needed
