name: Build Docker Image

on:
  push:
    branches:
      - main  # Change to your desired branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t your-image-name:latest .  # Change to your desired image name

      - name: List Docker images
        run: docker images
